version: '3.8'

services:
  db:
    image: postgres:13
    container_name: biblioteca_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  
  streamlit:
    build: .
    container_name: biblioteca_streamlit
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: ${DATABASE_URL}
