version: '3.8'

services:
  db:
    image: postgres:13
    container_name: biblioteca_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_container
    ports:
      - "8501:8501"  # Mapeando a porta do host para o contêiner
    volumes:
      - .:/app
    env_file:
      - .env